name: kentuckyhorseshoeingschool
favicon: null
layout_spectrum: 0.4233361145015806
typography_spectrum: 0.83682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f60300'
    - '#8b7d7a'
    - '#b3b0b0'
    - '#e05656'
  brandStrength: 0.27808694378472865
  lightness: 0.9291876000352204
  saturation: 0.2632991271093488
  rhythmicContrast: 0.3816437066998333
purpose: []
