name: kentuckyhorseshoeingschool
favicon: null
layout_spectrum: 0.4233361145015806
typography_spectrum: 0.7844252220820636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27808694378472865
  lightness: 0.9291876000352204
  saturation: 0.2632991271093488
  rhythmicContrast: 0.3816437066998333
purpose: []
